package lexer;
 
/**
 *  This file is automatically generated<br>
 *  - it contains the enumberation of all of the tokens
*/
public enum Tokens {
  BogusToken,Program,Int,Float,Char,
    string,ScientificN,BOOLean,If,Then,
    Else,Do,While,For,Function,
    Return,Identifier,INTeger,FLOAT,CHAR,
    STRING,SCIentificN,LeftBrace,RightBrace,LeftParen,
    RightParen,Comma,Assign,Equal,NotEqual,
    Less,LessEqual,Plus,Minus,Or,
    And,Multiply,Divide,Comment,semiColon,
    Power,Not
}
